export const EXERCISES = [
  { name: 'Bench Press', muscle: 'Chest', icon: 'ti-barbell', diff: 'Medium' },
  { name: 'Pull-Up', muscle: 'Back', icon: 'ti-arrow-up', diff: 'Hard' },
  { name: 'Squat', muscle: 'Legs', icon: 'ti-arrow-down-circle', diff: 'Hard' },
  { name: 'Shoulder Press', muscle: 'Shoulders', icon: 'ti-arrows-up', diff: 'Medium' },
  { name: 'Plank Hold', muscle: 'Core', icon: 'ti-shield', diff: 'Easy' },
  { name: 'Deadlift', muscle: 'Back', icon: 'ti-trending-up', diff: 'Hard' },
];

export const PROGRAMS = [
  { name: 'Strength Builder', desc: 'Progressive overload fundamentals', meta: ['12 Weeks', 'Intermediate'], icon: 'ti-barbell' },
  { name: 'Fat Burn HIIT', desc: 'High-intensity calorie torcher', meta: ['6 Weeks', 'Beginner'], icon: 'ti-flame' },
  { name: 'Mobility & Flex', desc: 'Flexibility and recovery focused', meta: ['4 Weeks', 'All Levels'], icon: 'ti-yoga' },
  { name: 'Powerlifting', desc: 'Competition prep program', meta: ['16 Weeks', 'Advanced'], icon: 'ti-trophy' },
  { name: 'Cardio Base', desc: 'Build cardiovascular endurance', meta: ['8 Weeks', 'Beginner'], icon: 'ti-heartbeat' },
  { name: 'Athletic Performance', desc: 'Sport-specific conditioning', meta: ['10 Weeks', 'Advanced'], icon: 'ti-run' },
];

export const SAVED = [
  { name: 'My Push Day', ex: 8, ago: '2 days ago' },
  { name: 'Leg Day Heavy', ex: 6, ago: '4 days ago' },
  { name: 'Morning Stretch', ex: 10, ago: 'Today' },
];

export const NOTIFS = [
  { title: 'Workout reminder', body: 'You have Upper Body Blast scheduled for today', time: '2h ago', unread: true },
  { title: 'New program available', body: 'Fat Burn HIIT has been updated with new exercises', time: '5h ago', unread: true },
  { title: 'Streak milestone', body: "You've hit a 5-day streak! Keep it going.", time: '1d ago', unread: true },
  { title: 'Goal updated', body: 'Weekly calorie goal adjusted to 3,000', time: '3d ago', unread: false },
  { title: 'New exercise added', body: 'Try the new Romanian Deadlift variation', time: '5d ago', unread: false },
];

export const WEEK = [
  { day: 'MON', num: 5, done: false },
  { day: 'TUE', num: 6, done: true },
  { day: 'WED', num: 7, done: false },
  { day: 'THU', num: 8, done: true },
  { day: 'FRI', num: 9, done: true },
  { day: 'SAT', num: 10, done: false },
  { day: 'SUN', num: 11, done: false },
];

export const GOALS = [
  { label: 'Workouts per week', val: '4/5', pct: 80 },
  { label: 'Weekly hours', val: '3.5h/5h', pct: 70 },
  { label: 'Streak goal', val: '8/14 days', pct: 57 },
  { label: 'Calorie burn', val: '2100/3000', pct: 70 },
];

export const CATS = ['All', 'Chest', 'Back', 'Legs', 'Core', 'Shoulders'];

export const NAV_ITEMS = [
  { key: 'home', label: 'Home', icon: 'ti-layout-dashboard' },
  { key: 'exercises', label: 'Exercises', icon: 'ti-stretching' },
  { key: 'explore', label: 'Explore', icon: 'ti-compass' },
  { key: 'library', label: 'Library', icon: 'ti-books' },
  { key: 'progress', label: 'Progress', icon: 'ti-chart-bar' },
  { key: 'profile', label: 'Profile', icon: 'ti-user' },
  { key: 'notifs', label: 'Notifications', icon: 'ti-bell' },
];

export const API_EXERCISES = [
  {
      "id": "2",
      "name": "Bench Press",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/00251101-Barbell-Bench-Press_Chest-FIX_small.png",
      "video_name": "qU9tbGJ8UFc",
      "equipment_id": "[\"1\"]",
      "body_part_id": "[\"2\"]",
      "Target_muscles_id": "[\"25\"]",
      "Synergist_muscles_id": "[\"8\",\"24\",\"44\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/00251201-Barbell-Bench-Press_Chest-FIX2_.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "573508"
  },
  {
      "id": "107",
      "name": "Triceps Pushdown",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/02411101-Cable-Triceps-Pushdown-(V-bar-attachment)_Upper-Arms_small.png",
      "video_name": "L3VDjqU49U8",
      "equipment_id": "[\"3\"]",
      "body_part_id": "[\"18\",\"5\"]",
      "Target_muscles_id": "[\"44\"]",
      "Synergist_muscles_id": "null",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/02411201-Cable-Triceps-Pushdown-(V-bar-attachment)_Upper-Arms.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "532491"
  },
  {
      "id": "212",
      "name": "Lever Leg Extension",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/05851101-Lever-Leg-Extension_Thighs_small.png",
      "video_name": "yHR-2qFmj5o",
      "equipment_id": "[\"6\"]",
      "body_part_id": "[\"19\",\"1\"]",
      "Target_muscles_id": "[\"27\"]",
      "Synergist_muscles_id": "null",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/05851201-Lever-Leg-Extension_Thighs.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "501968"
  },
  {
      "id": "145",
      "name": "Lateral Raise",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/03341101-Dumbbell-Lateral-Raise_shoulder-AFIX_small.png",
      "video_name": "Ex4j-lkLqTE",
      "equipment_id": "[\"4\"]",
      "body_part_id": "[\"6\"]",
      "Target_muscles_id": "[\"9\"]",
      "Synergist_muscles_id": "[\"8\",\"31\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/03341201-Dumbbell-Lateral-Raise_shoulder-FIX_.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "493394"
  },
  {
      "id": "219",
      "name": "Lever Seated Fly",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/05961101-Lever-Seated-Fly_Chest_small.png",
      "video_name": "XKaAozXQiYo",
      "equipment_id": "[\"6\"]",
      "body_part_id": "[\"2\"]",
      "Target_muscles_id": "[\"25\",\"8\"]",
      "Synergist_muscles_id": "[\"4\",\"24\",\"31\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/05961201-Lever-Seated-Fly_Chest-FIX_.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "461712"
  },
  {
      "id": "134",
      "name": "Hammer Curl",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/03121101-Dumbbell-Hammer-Curl-II_Upper-Arms_small.png",
      "video_name": null,
      "equipment_id": "[\"4\"]",
      "body_part_id": "[\"17\"]",
      "Target_muscles_id": "[\"4\",\"5\"]",
      "Synergist_muscles_id": "[\"6\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/03121201-Dumbbell-Hammer-Curl-(version-2)_Upper-Arms-FIX_.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "344803"
  },
  {
      "id": "105",
      "name": "Straight Back Seated Row",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/02391101-Cable-Straight-Back-Seated-Row_Back_small.png",
      "video_name": "NOjRbKrwwiI",
      "equipment_id": "[\"3\"]",
      "body_part_id": "[\"4\"]",
      "Target_muscles_id": "[\"19\",\"20\",\"37\",\"38\",\"41\",\"42\"]",
      "Synergist_muscles_id": "[\"5\",\"6\",\"10\",\"25\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/02391201-Cable-Straight-Back-Seated-Row_Back.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "338157"
  },
  {
      "id": "136",
      "name": "Incline Bench Press",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/03141101-Dumbbell-Incline-Bench-Press_Chest_small.png",
      "video_name": null,
      "equipment_id": "[\"4\"]",
      "body_part_id": "[\"2\"]",
      "Target_muscles_id": "[\"24\"]",
      "Synergist_muscles_id": "[\"8\",\"44\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/03141201-Dumbbell-Incline-Bench-Press_Chest-FIX2_.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "303726"
  },
  {
      "id": "1765",
      "name": "Dumbbell Incline Bench Press",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/03141101-Dumbbell-Incline-Bench-Press_Chest-FIX_small.png",
      "video_name": null,
      "equipment_id": "[\"4\"]",
      "body_part_id": "[\"2\"]",
      "Target_muscles_id": "[\"24\",\"25\"]",
      "Synergist_muscles_id": "[\"8\",\"44\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/03141201-Dumbbell-Incline-Bench-Press_Chest-FIX2_.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "290578"
  },
  {
      "id": "176",
      "name": "Seated Shoulder Press",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/04051101-Dumbbell-Seated-Shoulder-Press_Shoulders_small.png",
      "video_name": "sf5ESHpbgJk",
      "equipment_id": "[\"4\"]",
      "body_part_id": "[\"6\"]",
      "Target_muscles_id": "[\"8\"]",
      "Synergist_muscles_id": "[\"9\",\"24\",\"31\",\"44\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/04051201-Dumbbell-Seated-Shoulder-Press_Shoulders-FIX_.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "281798"
  },
  {
      "id": "58",
      "name": "Bar Lateral Pulldown",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/01501101-Cable-Bar-Lateral-Pulldown_Back_small.png",
      "video_name": "JjdBiQjtESQ",
      "equipment_id": "[\"3\"]",
      "body_part_id": "[\"4\"]",
      "Target_muscles_id": "[\"20\"]",
      "Synergist_muscles_id": "[\"5\",\"6\",\"10\",\"19\",\"37\",\"38\",\"41\",\"42\",\"4\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/01501201-Cable-Bar-Lateral-Pulldown_Back.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "272230"
  },
  {
      "id": "222",
      "name": "Lever Seated Leg Curl",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/05991101-Lever-Seated-Leg-Curl_Thighs-FIX_small.png",
      "video_name": "1SaYpphpQ5w",
      "equipment_id": "[\"6\"]",
      "body_part_id": "[\"20\",\"1\"]",
      "Target_muscles_id": "[\"17\"]",
      "Synergist_muscles_id": "[\"12\",\"29\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/05991201-Lever-Seated-Leg-Curl_Thighs.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "254455"
  },
  {
      "id": "213",
      "name": "Lever Lying Leg Curl",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/05861101-Lever-Lying-Leg-Curl_Thighs_small.png",
      "video_name": "II2eueH2qxE",
      "equipment_id": "[\"6\"]",
      "body_part_id": "[\"20\",\"1\"]",
      "Target_muscles_id": "[\"17\"]",
      "Synergist_muscles_id": "[\"12\",\"32\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/05861201-Lever-Lying-Leg-Curl_Thighs.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "248919"
  },
  {
      "id": "1651",
      "name": "Cable Pushdown ",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/02001101-Cable-Pushdown-(with-rope-attachment)_Upper-Arms_small.png",
      "video_name": "Nz794P2hD7Q",
      "equipment_id": "[\"3\"]",
      "body_part_id": "[\"18\",\"5\"]",
      "Target_muscles_id": "[\"44\"]",
      "Synergist_muscles_id": "null",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/02001201-Cable-Pushdown-(with-rope-attachment)_Upper-Arms.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "246003"
  },
  {
      "id": "117",
      "name": "Dumbbell Bench Press",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/02891101-Dumbbell-Bench-Press_Chest_small.png",
      "video_name": "Wsa-PRQoxNI",
      "equipment_id": "[\"4\"]",
      "body_part_id": "[\"2\"]",
      "Target_muscles_id": "[\"24\",\"25\"]",
      "Synergist_muscles_id": "[\"8\",\"44\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/02891201-Dumbbell-Bench-Press_Chest-FIX_.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "239173"
  },
  {
      "id": "371",
      "name": "Lever Seated Shoulder Press",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/14541101-Lever-Seated-Shoulder-Press_Shoulders_small.png",
      "video_name": null,
      "equipment_id": "[\"6\"]",
      "body_part_id": "[\"6\"]",
      "Target_muscles_id": "[\"8\"]",
      "Synergist_muscles_id": "[\"9\",\"24\",\"31\",\"44\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/14541201-Lever-Seated-Shoulder-Press_Shoulders_.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "238269"
  },
  {
      "id": "18",
      "name": "Full Squat",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/00431101-Barbell-Full-Squat_Thighs_small.png",
      "video_name": "qO1ezyI3c4E",
      "equipment_id": "[\"1\"]",
      "body_part_id": "[\"19\"]",
      "Target_muscles_id": "[\"13\",\"27\"]",
      "Synergist_muscles_id": "[\"32\",\"17\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/00431201-Barbell-Full-Squat_Thighs.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "230543"
  },
  {
      "id": "229",
      "name": "Pull-up",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/06521101-Pull-up_Back_small.png",
      "video_name": "yOu_Rv6L7Qs",
      "equipment_id": "[\"2\"]",
      "body_part_id": "[\"4\"]",
      "Target_muscles_id": "[\"20\",\"4\"]",
      "Synergist_muscles_id": "[\"5\",\"6\",\"10\",\"19\",\"37\",\"38\",\"41\",\"42\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/06521201-Pull-up_Back-FIX_.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "226189"
  },
  {
      "id": "1678",
      "name": "Cable Standing Fly",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/02271101-Cable-Standing-Fly_Chest-FIX_small.png",
      "video_name": "gOlaGpHTSi8",
      "equipment_id": "[\"3\"]",
      "body_part_id": "[\"2\"]",
      "Target_muscles_id": "[\"25\"]",
      "Synergist_muscles_id": "[\"8\",\"24\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/02271201-Cable-Standing-Fly_Chest.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "224569"
  },
  {
      "id": "223",
      "name": "Lever Seated Reverse Fly",
      "instructions": "",
      "image_name": "https://apilyfta.com/static/GymvisualPNG/06021101-Lever-Seated-Reverse-Fly_Shoulders_small.png",
      "video_name": "xJjrR1mX1Lg",
      "equipment_id": "[\"6\"]",
      "body_part_id": "[\"6\"]",
      "Target_muscles_id": "[\"10\"]",
      "Synergist_muscles_id": "[\"9\",\"19\",\"38\",\"41\",\"42\"]",
      "video_file": "https://apilyfta.com/static/GymvisualMP4/06021201-Lever-Seated-Reverse-Fly_Shoulders.mp4",
      "user_id": null,
      "exercise_type": "weight_reps",
      "is_favorite": null,
      "usage_count": "212573"
  }
];
